cc_test(
    name = "cast_to_tacky_test",
    size = "small",
    srcs = ["cast_to_tacky_test.cc"],
    deps = [
        "@googletest//:gtest",
        "//src/ast:ast",
        "//src/ir:ir",
        "//src/backend:backend",
        "//src/lexer:lexer",
        "//src/parser:parser",
    ],
)
