cc_test(
    name = "codegen_test",
    size = "small",
    srcs = ["codegen_test.cc"],
    deps = [
        "@googletest//:gtest",
        "//src/ast:ast",
        "//src/codegen:codegen",
        "//src/lexer:lexer",
        "//src/parser:parser",
        "//src/tacky:tacky",
        "//src/asm:asm",
    ],
)

cc_test(
    name = "cast_to_tacky_test",
    size = "small",
    srcs = ["cast_to_tacky_test.cc"],
    deps = [
        "@googletest//:gtest",
        "//src/ast:ast",
        "//src/codegen:codegen",
        "//src/lexer:lexer",
        "//src/parser:parser",
        "//src/tacky:tacky",
        "//src/asm:asm",
    ],
)