cc_test(
    name = "codegen_test",
    size = "small",
    srcs = ["codegen_test.cc"],
    deps = [
        "@googletest//:gtest",
        "//src/ast:ast",
        "//src/codegen:codegen",
        "//src/lexer:lexer",
        "//src/parser:parser",
    ],
)