load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ast",
    srcs = [],
    hdrs = ["c.h", "tacky.h", "x86_64_asm.h"],
    deps = [],
    visibility = ["//visibility:public"],
)