load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ast",
    srcs = ["ast.cc", "ast_graphviz.cc"],
    hdrs = ["ast.h", "type.h", "ast_graphviz.h"],
    deps = [],
    visibility = ["//visibility:public"],
)