cc_test(
    name = "parser_test",
    size = "small",
    srcs = ["parser_test.cc"],
    deps = [
        "@googletest//:gtest",
        "//src/parser:parser",
        "//src/ast:ast",
        "//src/lexer:lexer",
    ],
)