cc_test(
    name = "semantic_test",
    size = "small",
    srcs = ["typecheck_test.cc"],
    deps = [
        "@googletest//:gtest",
        "//src/ast:ast",
        "//src/lexer:lexer",
        "//src/parser:parser",
        "//src/semantic:semantic",
    ],
)