load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "asm",
    srcs = [],
    hdrs = ["asm_ast.h"],
    deps = [],
    visibility = ["//visibility:public"],
)