load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "semantic",
    srcs = [],
    hdrs = ["semantic.h"],
    deps = [
        "//src/ast:ast",
    ],
    visibility = ["//visibility:public"],
)